My_Boardgames_List/app/routes.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, session, flash
from app.models import Usuario, Jogos, Rank
from app import db
from sqlalchemy.orm import sessionmaker


def is_logged_in():
    return 'user_id' in session


# criação de um blueprint para rotas principais
main_routes = Blueprint('main_routes', __name__)

@main_routes.route('/', methods=['POST', 'GET'])
def index():
    # criando as variaveis e recebendo os valores do GET
    query = Jogos.query
    filterQuery = query

    try:
        user = session['user']
    except:
        KeyError
        user = 0

    

    jogadores = request.form.get('jogadores', 0)
    categoria = request.form.get('categoria', None)
    tempo = int(request.form.get('tempo', 9999))
    dono = request.form.get('dono', None)
    # "LIMPANDO" os valores do filtro
    if dono == 'null':
        dono = None

    if categoria == 'null':
        categoria = None
    
    # lidando em caso de erro na transformação de tempo e de jogadores
    try:
        jogadores = int(jogadores)
    except ValueError:
        jogadores = 0

    try:
        tempo = int(tempo)
    except ValueError:
        tempo = 9999
    # checando se houve algum input no filtro e o aplicando
    if jogadores > 0:
        query = query.filter(
            Jogos.nmJogadorMin <= jogadores,
            Jogos.nmJogadorMax >= jogadores
            )

    if dono != None:
        query = query.filter(
            Jogos.dono == dono
        )
    if categoria != None:
        query = query.filter(
            Jogos.categoria == categoria
        )
    
    jogos = query.all()
    
    # criando uma lista de categorias unicas dos jogos
    categList = filterQuery.with_entities(Jogos.categoria).all()
    categList = list(set(categList))
    for index in range(len(categList)):#limpando (' ',) da lista
        itemCategoria = str(categList[index])
        categList[index] = itemCategoria[2:-3:]
    
    # criando uma lista de donos unicos dos jogos
    donoList = filterQuery.with_entities(Jogos.dono).all()
    donoList = list(set(donoList))
    for index in range(len(donoList)):#limpando (' ',) da lista
        itemDono = str(donoList[index])
        donoList[index] = itemDono[2:-3:]

    # essas listas são usadas para criar todas as categorias no site
    # e receber o valor tambem

    rank = db.session.query(Rank).filter(Rank.id_user == user).all()
    ranks_dict = {r.id_game: r.nota for r in rank}

    
    return render_template('index.html', jogos=jogos,
                           categList=categList,
                           donoList=donoList,
                           ranks=ranks_dict
                           )


    # Receber Valor da Nota do Usurario
@main_routes.route('/rate', methods=['GET', 'POST'])
def rate():
    if request.method == 'POST' and request.form.get('user_id') != '':

        id_user = request.form.get('user_id')
        id_game = request.form.get('jogo_id')
        nota = request.form.get('nota')
        print(f"Nota: {nota}, ID Usuário: {id_user}, ID Jogo: {id_game}") 
        nota_existente = Rank.query.filter_by(id_user=id_user, id_game=id_game).first()

        
        if nota_existente:
            nota_existente.nota = nota
            db.session.commit()

        else:

            nova_votacao = Rank(id_game=id_game, nota=nota, id_user=id_user)
            db.session.add(nova_votacao)
            db.session.commit()

    else:
        return redirect(url_for('main_routes.login'))


    return redirect(url_for('main_routes.index'))

        

@main_routes.route('/login', methods=['GET', 'POST'])
def login():
    if 'user' in session:
        return redirect(url_for('main_routes.perfil'))
    
    if request.method == 'POST':
        login = request.form.get('login')
        senha = request.form.get('senha')
        
        usuario_existente = Usuario.query.filter_by(login=login).first()


        
        if usuario_existente and usuario_existente.check_password(senha):


            session['user'] = usuario_existente.id
            flash('Login efetuado')
            return redirect(url_for('main_routes.perfil'))
            
        else:
            print('invalido')
            
            #new_user = Usuario(login=login)
            #new_user.set_password(senha)
            #db.session.add(new_user)
            #db.session.commit()

    return render_template('login.html')

@main_routes.route('/perfil', methods=['GET', 'POST'])
def perfil():
    if 'user' in session:
        user = session['user']
        return render_template('Perfil.html', user=user)

@main_routes.route('/logout')
def logout():
    session.pop('user', None)
    return redirect(url_for('main_routes.login'))

My_Boardgames_List/app/routes/graph_routes.py
# Import necessário
import matplotlib.pyplot as plt
import io
import base64
from flask import Blueprint, render_template, Response
from app.models import Usuario, Jogos, Notas
from app.utils.ranking_helpers import calcular_ranking, botão_da_loucura

graph_routes = Blueprint('graph_routes', __name__)

@graph_routes.route('/graficos')
def cluster_user_avaliacao():
    # Dados de exemplo
    x = [1, 2, 3, 4]
    y = [10, 20, 25, 30]

    #Segmentação de Usuários com Clustering:
    #Pergunta: Podemos agrupar os usuários com base em seus padrões de avaliação?

    #Objetivo: Identificar diferentes tipos de jogadores, como aqueles que preferem jogos mais complexos ou aqueles que sempre dão notas altas.
    
    #Análise: Você pode aplicar técnicas de clustering (como K-means ou DBSCAN) para segmentar os usuários com base nas avaliações que eles deram. Isso pode gerar insights sobre perfis de jogadores.

    # Criando o gráfico de linha
    plt.figure()
    plt.scatter(x, y)
    plt.title("Exemplo de Gráfico de Linha")
    plt.xlabel("Eixo X")
    plt.ylabel("Eixo Y")

    # Salvando o gráfico em um buffer
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)

    # Convertendo o gráfico em uma string base64
    image_base64 = base64.b64encode(buf.getvalue()).decode('utf-8')
    buf.close()

    # Passando a string para o template
    return render_template('graficos.html', grafico=image_base64)

My_Boardgames_List/app/routes/main_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from app.models import Usuario, Jogos, Notas
from app.utils.ranking_helpers import calcular_ranking, botão_da_loucura
from app import db
#from sqlalchemy.orm import sessionmaker


def is_logged_in():
    return 'user_id' in session


# criação de um blueprint para rotas principais
main_routes = Blueprint('main_routes', __name__)

@main_routes.route('/', methods=['POST', 'GET'])
def index():
    # criando as variaveis e recebendo os valores do GET
    query = Jogos.query
    filterQuery = query

    try:
        user = session['user']
    except:
        KeyError
        user = 0

    

    jogadores = request.form.get('jogadores', 0)
    categoria = request.form.get('categoria', None)
    tempo = int(request.form.get('tempo', 9999))
    dono = request.form.get('dono', None)
    # "LIMPANDO" os valores do filtro
    if dono == 'null':
        dono = None

    if categoria == 'null':
        categoria = None
    
    # lidando em caso de erro na transformação de tempo e de jogadores
    try:
        jogadores = int(jogadores)
    except ValueError:
        jogadores = 0

    try:
        tempo = int(tempo)
    except ValueError:
        tempo = 9999
    # checando se houve algum input no filtro e o aplicando
    if jogadores > 0:
        query = query.filter(
            Jogos.nmJogadorMin <= jogadores,
            Jogos.nmJogadorMax >= jogadores
            )

    if dono != None:
        query = query.filter(
            Jogos.dono == dono
        )
    if categoria != None:
        query = query.filter(
            Jogos.categoria == categoria
        )
    
    jogos = query.order_by(Jogos.rankInHouse).all()
    
    # criando uma lista de categorias unicas dos jogos
    categList = filterQuery.with_entities(Jogos.categoria).all()
    categList = list(set(categList))
    for index in range(len(categList)):#limpando (' ',) da lista
        itemCategoria = str(categList[index])
        categList[index] = itemCategoria[2:-3:]
    
    # criando uma lista de donos unicos dos jogos
    donoList = filterQuery.with_entities(Jogos.dono).all()
    donoList = list(set(donoList))
    for index in range(len(donoList)):#limpando (' ',) da lista
        itemDono = str(donoList[index])
        donoList[index] = itemDono[2:-3:]

    # essas listas são usadas para criar todas as categorias no site
    # e receber o valor tambem

    #############################
    nota = db.session.query(Notas).filter(Notas.id_user == user).all()
    notas_dict = {r.id_game: r.nota for r in nota}
    #############################

    


    
    return render_template('index.html', jogos=jogos,
                           categList=categList,
                           donoList=donoList,
                           notas=notas_dict
                           )


    # Receber Valor da Nota do Usurario
@main_routes.route('/rate', methods=['GET', 'POST'])
def rate():
    if request.method == 'POST' and request.form.get('user_id') != '':

        id_user = request.form.get('user_id')
        id_game = request.form.get('jogo_id')
        nota = request.form.get('nota')
        print(f"Nota: {nota}, ID Usuário: {id_user}, ID Jogo: {id_game}") 
        nota_existente = Notas.query.filter_by(id_user=id_user, id_game=id_game).first()

        
        if nota_existente:
            nota_existente.nota = nota
            db.session.commit()
            calcular_ranking()

        else:

            nova_votacao = Notas(id_game=id_game, nota=nota, id_user=id_user)
            db.session.add(nova_votacao)
            db.session.commit()
            calcular_ranking()

    else:
        return redirect(url_for('main_routes.login'))


    return redirect(url_for('main_routes.index'))

        

@main_routes.route('/login', methods=['GET', 'POST'])
def login():
    if 'user' in session:
        return redirect(url_for('main_routes.perfil'))
    
    if request.method == 'POST':
        login = request.form.get('login')
        senha = request.form.get('senha')
        
        usuario_existente = Usuario.query.filter_by(login=login).first()


        
        if usuario_existente and usuario_existente.check_password(senha):


            session['user'] = usuario_existente.id
            flash('Login efetuado')
            return redirect(url_for('main_routes.perfil'))
            
        else:
            print('invalido')
            
            #new_user = Usuario(login=login)
            #new_user.set_password(senha)
            #db.session.add(new_user)
            #db.session.commit()

    return render_template('login.html')

@main_routes.route('/perfil', methods=['GET', 'POST'])
def perfil():
    if 'user' in session:
        user = session['user']
        return render_template('Perfil.html', user=user)

@main_routes.route('/logout')
def logout():
    session.pop('user', None)
    return redirect(url_for('main_routes.login'))

#apenas para testes
@main_routes.route('/gerar_notas')
def gerar_notas():

    botão_da_loucura()
    calcular_ranking()
    return redirect(url_for('main_routes.index'))

My_Boardgames_List/app/templates/Perfil.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {{user}}

    <button onclick="window.location.href='{{url_for('main_routes.index')}}'">
      Pagina Inicial
    </button>
    <button
      onclick="window.location.href='{{ url_for('main_routes.logout') }}'"
    >
      Logout
    </button>
  </body>
</html>

My_Boardgames_List/app/templates/graficos.html
<!-- graficos.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gráficos</title>
</head>
<body>
    <h1>Gráfico de Linha</h1>
    <img src="data:image/png;base64,{{ grafico }}" alt="Gráfico de Linha">
</body>
</html>

My_Boardgames_List/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}" />
    <title>Tabletop Lab</title>
    <style>
      @import url(//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css);
    </style>
  </head>
  <body>
    <div class="container">
      <!-- Header -->
      <header>
        <h1>Tabletop Lab</h1>
      </header>

      <!-- Conteúdo principal com filtro e tabela lado a lado -->
      <div class="main-content">
        <!-- Filtro de Jogos -->
        <section class="filter-section">
          <form method="POST" action="/">
            <div class="form-group">
              <label for="jogadores">Número de Jogadores</label>
              <input type="text" id="jogadores" name="jogadores" />
            </div>

            <div class="form-group">
              <label for="dono">Dono</label>
              <select name="dono">
                <option value="null">Todos</option>
                {% for categ in donoList %}
                <option value="{{ categ }}">
                  {{ categ.replace('_', ' ') }}
                </option>
                {% endfor %}
              </select>
            </div>

            <div class="form-group">
              <label for="categoria">Categoria</label>
              <select name="categoria">
                <option value="null">Todos</option>
                {% for categ in categList %}
                <option value="{{ categ }}">
                  {{ categ.replace('_', ' ') }}
                </option>
                {% endfor %}
              </select>
            </div>

            <button type="submit" class="btn-submit">Filtrar</button>
          </form>
          <button
            onclick="window.location.href='{{url_for('main_routes.login')}}'">
            fazer login
          </button>
          <button
            onclick="window.location.href='{{url_for('main_routes.gerar_notas')}}'">
            gerar notas
          </button>
          
          <button onclick="window.location.href='{{ url_for('graph_routes.cluster_user_avaliacao') }}'">
            Graficos
        </button>
        
        </section>

        <!-- Tabela de Jogos -->
        <section class="table-section">
          <h2>Tabela de Jogos</h2>
          <table>
            <thead>
              <tr>
                <th>Rank</th>
                <th></th>
                <th>Nome</th>
                <th>N. Jogadores</th>
                <th>Categoria</th>
                <th>Dificuldade</th>
                <th>Duração</th>
                <th>Dono</th>
              </tr>
            </thead>
            <tbody>
              {% for jogo in jogos %}
              <tr>
                <!-- ######################################################### -->
                <td class="small-column">{{ jogo.rankInHouse }}</td>
                <!-- ######################################################### -->
            
                <td class="game_img">
                  <div class="image-container">
                    <img src="{{ jogo.img }}" class="game-img" />
                  </div>
                </td>
            
                <td class="big-column">{{ jogo.nome }}</td>
                <td class="small-column">
                  {{ jogo.nmJogadorMin }} - {{ jogo.nmJogadorMax }}
                </td>
            
                <td class="mid-column">
                  <!-- ESTRELAS NOTAS AQUI -->
                  <form action="/rate" method="POST"> 
                    <fieldset class="rate">
                      <input type="radio" id="rating10-{{ jogo.id }}" name="nota" value="10" {% if jogo.id in notas and notas[jogo.id] == 10 %}checked{% endif %} onchange="this.form.submit()" />
                      <label for="rating10-{{ jogo.id }}" title="5 stars"></label>
            
                      <input type="radio" id="rating9-{{ jogo.id }}" name="nota" value="9" {% if jogo.id in notas and notas[jogo.id] == 9 %}checked{% endif %} onchange="this.form.submit()" />
                      <label class="half" for="rating9-{{ jogo.id }}" title="4 1/2 stars"></label>
            
                      <input type="radio" id="rating8-{{ jogo.id }}" name="nota" value="8" {% if jogo.id in notas and notas[jogo.id] == 8 %}checked{% endif %} onchange="this.form.submit()" />
                      <label for="rating8-{{ jogo.id }}" title="4 stars"></label>
            
                      <input type="radio" id="rating7-{{ jogo.id }}" name="nota" value="7" {% if jogo.id in notas and notas[jogo.id] == 7 %}checked{% endif %} onchange="this.form.submit()" />
                      <label class="half" for="rating7-{{ jogo.id }}" title="3 1/2 stars"></label>
            
                      <input type="radio" id="rating6-{{ jogo.id }}" name="nota" value="6" {% if jogo.id in notas and notas[jogo.id] == 6 %}checked{% endif %} onchange="this.form.submit()" />
                      <label for="rating6-{{ jogo.id }}" title="3 stars"></label>
            
                      <input type="radio" id="rating5-{{ jogo.id }}" name="nota" value="5" {% if jogo.id in notas and notas[jogo.id] == 5 %}checked{% endif %} onchange="this.form.submit()" />
                      <label class="half" for="rating5-{{ jogo.id }}" title="2 1/2 stars"></label>
            
                      <input type="radio" id="rating4-{{ jogo.id }}" name="nota" value="4" {% if jogo.id in notas and notas[jogo.id] == 4 %}checked{% endif %} onchange="this.form.submit()" />
                      <label for="rating4-{{ jogo.id }}" title="2 stars"></label>
            
                      <input type="radio" id="rating3-{{ jogo.id }}" name="nota" value="3" {% if jogo.id in notas and notas[jogo.id] == 3 %}checked{% endif %} onchange="this.form.submit()" />
                      <label class="half" for="rating3-{{ jogo.id }}" title="1 1/2 stars"></label>
            
                      <input type="radio" id="rating2-{{ jogo.id }}" name="nota" value="2" {% if jogo.id in notas and notas[jogo.id] == 2 %}checked{% endif %} onchange="this.form.submit()" />
                      <label for="rating2-{{ jogo.id }}" title="1 star"></label>
            
                      <input type="radio" id="rating1-{{ jogo.id }}" name="nota" value="1" {% if jogo.id in notas and notas[jogo.id] == 1 %}checked{% endif %} onchange="this.form.submit()" />
                      <label class="half" for="rating1-{{ jogo.id }}" title="1/2 star"></label>
            
                      <input type="hidden" name="jogo_id" value="{{ jogo.id }}" />
                      <input type="hidden" name="user_id" value="{{ session['user'] }}" />
                    </fieldset>
                  </form>
                  <!-- FIM DE ESTRELAS DE NOTAS -->
                </td>
            
                <td class="small-column">{{ jogo.dificuldade }}/5</td>
                <td class="small-column">{{ jogo.tempoDeJogo }} Min</td>
                <td>{{ jogo.dono }}</td>
              </tr>
              {% endfor %}
            </tbody>
            
            
          </table>
        </section>
      </div>

      <!-- Footer -->
      <footer>
        <p>Desenvolvido por Gustavo Carvalho</p>
      </footer>
    </div>
  </body>
</html>

My_Boardgames_List/app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form method="POST" action="/login">
      <label for="login">Login:</label>
      <input type="text" id="login" name="login" />

      <label for="senha">Senha:</label>
      <input type="password" id="senha" name="senha" />

      <button type="submit">Log in</button>
    </form>
  </body>
</html>

My_Boardgames_List/app/templates/sobre.html
<!--
I was in seek of a star rating system that used radio inputs for accessibility fallbacks and through some trial and error as well as the very robust solution by James Barnett I was able to 

Exploring many solutions:
fork of https://codepen.io/jamesbarnett/pen/vlpkh
http://lea.verou.me/2011/08/accessible-star-rating-widget-with-pure-css/
http://www.yuiblog.com/blog/2010/08/24/developing-an-accessible-star-ratings-widget/
https://css-tricks.com/star-ratings/
-->

<style>
  /* Base setup */
  @import url(//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css);

  body {
    margin: 5%;
    text-align: center;
    background: #111;
    color: #333;
  }

  h1 {
    font-size: 2em;
    margin-bottom: 0.5rem;
  }

  /* Ratings widget */
  .rate {
    display: inline-block;
    border: 0;
  }

  /* Hide radio */
  .rate > input {
    display: none;
  }

  /* Order correctly by floating highest to the right */
  .rate > label {
    float: right;
  }

  /* The star of the show */
  .rate > label:before {
    display: inline-block;
    font-size: 2rem;
    padding: 0.3rem 0.2rem;
    margin: 0;
    cursor: pointer;
    font-family: FontAwesome;
    content: "\f005 "; /* full star */
  }

  /* Half star trick */
  .rate .half:before {
    content: "\f089 "; /* half star no outline */
    position: absolute;
    padding-right: 0;
  }

  /* Click + hover color */
  input:checked ~ label, /* color current and previous stars on checked */
  label:hover, 
  label:hover ~ label {
    color: #73b100;
  } /* color previous stars on hover */

  /* Hover highlights */
  input:checked + label:hover, 
  input:checked ~ label:hover, /* highlight current and previous stars */
  input:checked ~ label:hover ~ label, /* highlight previous selected stars for new rating */
  label:hover ~ input:checked ~ label {
    /* highlight previous selected stars */
    color: #a6e72d;
  }
</style>

<section class="table-section">
  <h2>Tabela de Jogos</h2>
  <table>
    <thead>
      <tr>
        <th>Rank</th>
        <th></th>
        <th>Nome</th>
        <th>N. Jogadores</th>
        <th>Categoria</th>
        <th>Dificuldade</th>
        <th>Duração</th>
        <th>Dono</th>
      </tr>
    </thead>
    <tbody>
      {% for jogo in jogos %}
      <tr>
        <td class="small-column">{{ jogo.rankInHouse }}</td>

        <td class="game_img">
          <div class="image-container">
            <img src="{{ jogo.img }}" class="game-img" />
          </div>
        </td>

        <td class="big-column">{{ jogo.nome }}</td>
        <td class="small-column">
          {{ jogo.nmJogadorMin }} - {{ jogo.nmJogadorMax }}
        </td>

        <td class="mid-column">
          <!-- RANK DE ESTRELAS AQUI -->
          <form action="/submit_rating" method="POST">
            <fieldset class="rate">
              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="10" />
              <label for="{{ jogo.id }}" title="5 stars"></label>

              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="9" />
              <label
                class="half"
                for="{{ jogo.id }}"
                title="4 1/2 stars"></label>

              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="8" />
              <label for="{{ jogo.id }}" title="4 stars"></label>

              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="7" />
              <label
                class="half"
                for="{{ jogo.id }}"
                title="3 1/2 stars"></label>

              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="6" />
              <label for="{{ jogo.id }}" title="3 stars"></label>

              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="5" />
              <label
                class="half"
                for="{{ jogo.id }}"
                title="2 1/2 stars"></label>

              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="4" />
              <label for="{{ jogo.id }}" title="2 stars"></label>

              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="3" />
              <label
                class="half"
                for="{{ jogo.id }}"
                title="1 1/2 stars"></label>

              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="2" />
              <label for="{{ jogo.id }}" title="1 star"></label>

              <input
                type="radio"
                id="{{ jogo.id }}"
                name="rating-{{ jogo.id }}"
                value="1" />
              <label class="half" for="{{ jogo.id }}" title="1/2 star"></label>
            </fieldset>
          </form>
          <!-- FIM DE RANK DE ESTRELAS -->
        </td>

        <td class="small-column">{{ jogo.dificuldade }}/5</td>
        <td class="small-column">{{ jogo.tempoDeJogo }} Min</td>
        <td>{{ jogo.dono }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>